import './globals.css';
import Link from 'next/link';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <nav className="w-full bg-white border-b border-gray-200 py-3 px-6 flex gap-6 items-center shadow-sm mb-4">
          <Link href="/" className="font-bold text-blue-700 hover:underline">Home</Link>
          <Link href="/offers/add" className="font-semibold text-blue-600 hover:underline">Add Offer</Link>
          <Link href="/chat" className="font-semibold text-blue-600 hover:underline">Chat</Link>
        </nav>
        {children}
      </body>
    </html>
  )
}
